# Generated by Django 5.2.1 on 2025-06-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
